#pragma once
#include <opencv2/videoio/videoio.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/tracking.hpp>
#include <opencv2/objdetect.hpp>

/// <summary>
/// Class that handles everything relating to object tracking - essentially provides a nice little
/// wrapper around OpenCV's object tracker class
/// </summary>
class ObjectTracker
{
public:
	ObjectTracker(cv::Mat, cv::Rect);
	cv::Rect2d updateBox(cv::Mat);
	bool confirmTracker();

	~ObjectTracker();
private:
	/// <summary>
	/// Pointer to the actual median flow tracker object
	/// </summary>
	cv::Ptr<cv::TrackerMedianFlow> tracker;
	/// <summary>
	/// Bounding box that is updated every time the tracker updates
	/// </summary>
	cv::Rect2d box;
	/// <summary>
	/// Vector that records the history of previous bounding boxes generated by the tracker
	/// </summary>
	std::vector<cv::Rect2d> trackingHistory;
};

